---
networks:
  frontend:
    external: true

services:
  docker-radio-display:
    image: ghcr.io/mongstaen/docker-radio-display:latest
    container_name: docker-radio-display
    labels:
      - traefik.enable=true
      - traefik.http.routers.docker-radio-display-http.entrypoints=web
      - traefik.http.routers.docker-radio-display-http.rule=Host(`display.papa.party`)
      - traefik.http.routers.docker-radio-display-https.entrypoints=websecure
      - traefik.http.routers.docker-radio-display-https.rule=Host(`display.papa.party`)
      - traefik.http.routers.docker-radio-display-https.tls=true
      - traefik.http.routers.docker-radio-display-https.tls.certresolver=cloudflare
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - frontend

    restart: unless-stopped
