---
services:
  docker-radio-display:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-radio-display
    user: "0:0"
    environment:
      - PORT=3000
      - APPKEY=yourappkey
      - SWAGGER_USER=swagger
      - SWAGGER_PASSWORD=swagger
      - NODE_ENV=development
      # Right panel settings, if not set. Defaults to true.
      - DISPLAY_MICROPHONE=false
      - DISPLAY_AUTOMATION=true
      - DISPLAY_EOF=false
    ports:
      - "3000:${PORT:-3000}"
    # labels:
    #  - traefik.enable=true
    #  - traefik.http.routers.docker-radio-display-http.entrypoints=web
    #  - traefik.http.routers.docker-radio-display-http.rule=Host(``)
    #  - traefik.http.routers.docker-radio-display-https.entrypoints=websecure
    #  - traefik.http.routers.docker-radio-display-https.rule=Host(``)
    #  - traefik.http.routers.docker-radio-display-https.tls=true
    #  - traefik.http.routers.docker-radio-display-https.tls.certresolver=cloudflare
    #  - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["sh", "-c", "npm install && npm run dev"]